### ISSUE TITLE
[DOCS] 프로젝트를 진행하며 지켜야 할 기본적인 원칙

### ISSUE THREAD

**Issue by DongGeon0908** [o-ing/o-ing#1]
프로젝트를 진행하면서 지켜야 할 기본적인 원칙을 명세하는 것이 중요할 것 같습니다.
패키지 구조, API 명세, 요구사항 정리 등 앞으로 단기간 동안 우리가 해나가야 하는 일이 많은 것 같습니다.

프로젝트 진행시 필요할 것 같은 내용 혹은 도움이 될 것 같은 내용을 정리해서 해당 레포지터리에 올려주시면 좋을 것 같습니다!
@jinn2u

**Comment by jinn2u** [comment]
알겠습니다😀
